name: CI
on:
  - push
  - pull_request

jobs:
  build-linux:
    name: Linux-autoTests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Updates
      run: sudo apt-get update

    - name: Dependencies
      run: sudo apt-get install qtbase5-dev qt5-default qt5-qmake libqt5svg5-dev qtscript5-dev qttools5-dev libqt5svg5-dev zlib1g-dev pkg-config

    - name: Configure
      run: qmake texstudio.pro CONFIG+=debug NO_POPPLER_PREVIEW=1

    - name: Build
      run: make -j 2

    - name: Test
      run: QT_QPA_PLATFORM=offscreen ./texstudio --auto-tests

###################################

  build-linux-win:
    name: win build (mxe)
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Add mxe.cc repo
      run: |
        sudo apt-key adv \
        --keyserver keyserver.ubuntu.com \
        --recv-keys 86B72ED9 
        sudo add-apt-repository \
          "deb [arch=amd64] https://pkg.mxe.cc/repos/apt `lsb_release -sc` main" 
      
    - name: Updates
      run: sudo apt-get update

    - name: Dependencies
      run: |
        sudo apt-get install mxe-x86-64-w64-mingw32.shared-cairo \
             mxe-x86-64-w64-mingw32.shared-curl \
             mxe-x86-64-w64-mingw32.shared-freetype \
             mxe-x86-64-w64-mingw32.shared-glib \
             mxe-x86-64-w64-mingw32.shared-jpeg \
             mxe-x86-64-w64-mingw32.shared-lcms \
             mxe-x86-64-w64-mingw32.shared-libpng \
             mxe-x86-64-w64-mingw32.shared-libwebp \
             mxe-x86-64-w64-mingw32.shared-openjpeg \
             mxe-x86-64-w64-mingw32.shared-poppler \
             mxe-x86-64-w64-mingw32.shared-qtbase \
             mxe-x86-64-w64-mingw32.shared-qtdeclarative \
             mxe-x86-64-w64-mingw32.shared-qtscript \
             mxe-x86-64-w64-mingw32.shared-qttools \
             mxe-x86-64-w64-mingw32.shared-tiff \
             mxe-x86-64-w64-mingw32.shared-zlib \
             mxe-x86-64-w64-mingw32.static-nsis

    - name: Configure
      run: |
        MXEDIR="/usr/lib/mxe"
        MXETARGET="x86_64-w64-mingw32.shared"
        PATH=$PATH:${MXEDIR}/usr/bin
        $MXEDIR/usr/bin/${MXETARGET}-qmake-qt5 texstudio.pro CONFIG-=debug MXE=1 BUILD_ADWAITA=1

    - name: Build
      run: |
        MXEDIR="/usr/lib/mxe"
        MXETARGET="x86_64-w64-mingw32.shared"
        PATH=$PATH:${MXEDIR}/usr/bin
        make -j 2
      
    - name: Package
      run: |
        MXEDIR="/usr/lib/mxe"
        MXETARGET="x86_64-w64-mingw32.shared"
        PATH=$PATH:${MXEDIR}/usr/bin
        .github/scripts/package_win.sh
      
###################################

  build-linux-release:
    name: linux appimage
    runs-on: ubuntu-16.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Updates
      run: sudo apt-get update

    - name: Dependencies
      run: sudo apt-get install qtbase5-dev qt5-default qt5-qmake libqt5svg5-dev qtscript5-dev qttools5-dev libqt5svg5-dev libpoppler-qt5-dev pkg-config zlib1g-dev 

    - name: Configure
      run: qmake texstudio.pro CONFIG-=debug

    - name: Build
      run: make -j 2
      
    - name: Package
      run: ./.github/scripts/package_linux.sh
        
      
############################
      
  macosx-bintray:
    name: Mac OS X (Bintray)
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        # /usr/local/bin/2to3 is symlinked to the native python2 installation
        # but prevents the homebrew install from succeeding
        rm -f /usr/local/bin/2to3
        brew update > brew_update.log || { echo "::error::Updating homebrew failed"; cat brew_update.log; exit 1; }
        brew install poppler qt5

    - name: Configure
      run: qmake texstudio.pro
      working-directory: build

    - name: Build
      run: make -j
      working-directory: build

    - name: Package
      run: |
        macdeployqt texstudio.app -dmg
        sha256sum texstudio.dmg
   


